Update Join our Community links
OpenMined/openmined-website pull request #95
Opened 2021-04-15 00:40 UTC by Metrix1010

## Description
Join the Community link in homepage.js updated from Placements to Slack

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ ] My changes are covered by tests

2021-04-15 16:53 UTC, cereallarceny requested changes
See comment

2021-04-15 16:53 UTC, cereallarceny commented on src/content/homepage.js
> +    link: 'https://openmined.slack.com',
It's slack.openmined.org

2021-04-16 16:07 UTC, Metrix1010 commented on src/content/homepage.js
> +    link: 'https://openmined.slack.com',
I updated it to slack.openmined.org

2021-04-20 14:13 UTC, cereallarceny approved these changes

2021-04-20 14:13 UTC, merged